IF COL_LENGTH('dbo.TRATAMIENTOS', 'TipoPlan') IS NULL
    ALTER TABLE dbo.TRATAMIENTOS ADD TipoPlan nvarchar(20) NOT NULL
    CONSTRAINT DF_TRATAMIENTOS_TipoPlan DEFAULT N'continuo';
GO
IF COL_LENGTH('dbo.TRATAMIENTOS', 'DiasActivos') IS NULL
    ALTER TABLE dbo.TRATAMIENTOS ADD DiasActivos int NULL;
GO
IF COL_LENGTH('dbo.TRATAMIENTOS', 'DiasDescanso') IS NULL
    ALTER TABLE dbo.TRATAMIENTOS ADD DiasDescanso int NULL;
GO
IF COL_LENGTH('dbo.TRATAMIENTOS', 'CantidadCiclos') IS NULL
    ALTER TABLE dbo.TRATAMIENTOS ADD CantidadCiclos int NULL;
GO
